### ISSUE TITLE
In Out Parameter 

### ISSUE THREAD

**Issue by jigarce** [EnterpriseLibrary/data-access-application-block#14]
HI ,

Please add below in Database.cs for In & OUT parameter

 /// &lt;summary>
        /// Adds new In Out DbParamter object to given command
        /// &lt;/summary>
        /// &lt;param name="command">&lt;/// &lt;param name="name">&lt;/param>
        /// &lt;param name="dbType">&lt;/param>
        /// &lt;param name="value">&lt;/param>
        public void AddInOutParameter(DbCommand command, string name, DbType dbType, object value)
        {
            AddParameter(command, name, dbType, 0, ParameterDirection.InputOutput, true, 0, 0, String.Empty, DataRowVersion.Default, value);
        }

**Comment by Chavoshi** [comment]
Can you explain more about your request?
What is the problem that you are trying to fix it with this change?

**Comment by tsahi** [comment]
Hi @jigarce ,
Not that I'm complaining, but just to let you know, this isn't as simple as adding your code to Database class. first of all, I realized that you also need to add a size parameter, otherwise DAAB (or something along the way) sets the size to the size of the input value, and if the output value is bigger, it's truncated. Then we need to add test cases to SQL Server, Oracle, OLE DB and ODBC, each with a test method and test procedure. So I'm working on it, but it takes some time. Help is appreciated.

**Comment by jigarce** [comment]
@tsahi  , I would like to help but i dont have any idea except SQL Server ! :)

**Comment by tsahi** [comment]
This is done. Will be released with 7.0, unless someone here wants to make a minor release with it.
@Chavoshi 
@entlib
