### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by tsahi** [EnterpriseLibrary/data-access-application-block#8]
While looking to push DAAB forward, I found this project, and I have some questions.
1. Is this project alive? I went over the commits in /source folder, and only found configuration changes. Are there any real changes here compared to Entlib 6?
2. I found that under the @entlib user there are copies (not forks) of the entire enterprise library from @microsoftarchive. What version of EntLib have you started with? And why not fork?
3. Do you have a roadmap of planned features? I have a few ideas of my own, but I'd like to know if they align with yours.
4. Is this and other projects under the @entlib something "official", initiated by or supported by Microsoft in any way? Are you in contact with them? How many people are involved in it?
5. Most importantly, will you accept PRs?

**Comment by Chavoshi** [comment]
Hi,
Thanks for your interest on this project.

Actually this project is a only copy of EntLib6 enabled for .Net Core 2+ and there is no feature plan except resolving the current issues, but we are always open to new ideas and thinking of expanding the abilities of the EntLib, and for sure we accept PRs.

Just as an explanation, initially we had supposed to have Microsoft support for this project but now it is just managing by our small community.

The previous home of this project is here: https://github.com/Chavoshi/EnterpriseLibrary.NetCore

**Comment by tsahi** [comment]
I was thinking about things like
* support .NET Core, as well as .NET Framework
* expose TPL methods
* replace System.Data.SqlClient with Microsoft.Data.SqlClient
* Expose Database class as interface

**Comment by tsahi** [comment]
why is the Oracle.Tests.VSTS project excluded from the Data solution?

**Comment by tsahi** [comment]
I'm really undecided between contributing to this project, or starting my own fork. But if I wait for eight months for a reply, or the other guy waits for more than a month for a reply to a PR (#15 ), I really don't know if contributing here will be effective.

**Comment by Chavoshi** [comment]
> 
> 
> why is the Oracle.Tests.VSTS project excluded from the Data solution?

The reason is, at this time we do not have any accessible Oracle server externally and we just can run our Oracle tests in or internal network.

And for your second question, that PR is just for enabling the SourceLink, which we've not seen any reason to update the NuGet packages and version without having any visible changes, but it is going to be embedded in the next release and the PR will be accepted soon.

BTW, sorry for not responding in your inquiry here, but as I have explained it several times in other threads, this project is mostly created for supporting EntLib in .Net Core and its main focus is only on bug fixing, but we always appreciate adding new features by contributors like you.

For start, I do agree with all of your thoughts and you can add each feature in a separated branch.

**Comment by tsahi** [comment]
You can run the Oracle tests in the free Oracle XE edition. From the original connection strings it appears like this is what Microsoft were doing. I also did it in a fork I made to the repository at https://github.com/microsoftarchive/data-access-application-block.

Before making significant changes, I believe as many unit test as possible should be enabled. I checked out your repo and many tests fail. I suggest I'll start with fixes to these tests. What do you think?

**Comment by Chavoshi** [comment]
I totally agree with you. Go ahead.

Thanks,
